"""Init

Revision ID: 5596889eb51c
Revises: bd41ca5a4681
Create Date: 2024-01-15 09:29:05.947734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5596889eb51c'
down_revision: Union[str, None] = 'bd41ca5a4681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('additional_data', sa.String(), nullable=False))
    op.drop_column('contacts', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('completed', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'additional_data')
    # ### end Alembic commands ###
